#!/bin/sh

# need to compile in this order for the modules to work:
#gfortran -c msis_constants.F90
#gfortran -c msis_gfn.F90
#gfortran -c msis_tfn.F90
#gfortran -c msis_dfn.F90
#gfortran -c msis_calc.F90
#gfortran -c msis_gtd8d.F90
#gfortran -c msis_init.F90
#gfortran -c msis_utils.F90

gfortran -c msis_all.f90
gfortran -c msis2.1_test.F90

#gfortran -o msis2.1 msis*.o
gfortran -o msis2.1 msis2.1_test.o msis_all.o

g++ -c run_msis.cpp
gfortran -c call_msis.f90

g++ -o msis_c -lgfortran run_msis.o msis_all.o call_msis.o
