# (c) 2020, the Aether Development Team (see doc/dev_team.md for members)
# Full license can be found in License.md

COMPILE.CPP = g++
LINK.CPP = g++
AR = ar -rs

# FLAGS = -O3 -ffast-math -c -I/opt/local/include

# Can use this version for no optimization and no fast math:
FLAGS = -c -I/opt/local/include
