# (c) 2020, the Aether Development Team (see doc/dev_team.md for members)
# Full license can be found in License.md

COMPILE.CPP = g++
LINK.CPP = g++
AR = ar -rs

INCLUDE_DIR = /usr/include
LIB_DIR = /usr/lib/x86_64-linux-gnu
NETCDF = netcdf_c++4
