# (c) 2020, the Aether Development Team (see doc/dev_team.md for members)
# Full license can be found in License.md

COMPILE.CPP = g++
LINK.CPP = g++
AR = ar -rs

INCLUDE_DIR = /opt/local/include
LIB_DIR = /opt/local/lib
NETCDF = netcdf_c++4

FLAGS = -O3 -ffast-math -c -I/opt/local/include --std=c++11

# Can use this version for no optimization and no fast math:
# FLAGS = -c -I${INCLUDE_DIR} -I../include
