# This workflow will install the Aether code and eventually run tests

name: Compilation Test

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        cc: ["gcc-default"]
        cflag: ["-DUSE_NETCDF=Y", "", "-DUSE_DOUBLE_PRECISION=Y"]
        include:
          - os: "macos-latest"
            cc: "/usr/local/bin/gcc-13"

    name: ${{ matrix.cc }} on ${{ matrix.os }} with flag ${{ matrix.cflag }}
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3

    - name: Install Ubuntu dependencies
      if: startsWith(matrix.os, 'ubuntu')
      run: |
        sudo apt-get update
        cat requirements.linux | xargs sudo apt-get install

    - name: Install OSX dependencies
      if: startsWith(matrix.os, 'mac')
      run: |
        brew update
        brew upgrade
        cat requirements.mac | xargs brew install
        brew reinstall gcc

    - name: Ubuntu cmake configure
      if: startsWith(matrix.os, 'ubuntu')
      run: |
        mkdir build
        cd build
        cmake ${{ matrix.cflag }} ..
        make VERBOSE=1

    - name: Mac cmake configure
      if: startsWith(matrix.os, 'mac')
      run: |
        ls /usr/local/Cellar/lib/*netcdf*
        mkdir build
        cd build
        cmake ${{ matrix.cflag }} -DCMAKE_CXX_COMPILER=${{ matrix.cc }} ..
        make VERBOSE=1

    - name: Test run
      run: |
        cp -R share/run ./run_test
        cd run_test
        ./aether
