# This workflow will install the Aether code and eventually run tests

name: Compilation Test

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        cc: ["gcc"]
        cxx: ["g++"]
        cflag: ["-DUSE_NETCDF=Y", "", "-DUSE_DOUBLE_PRECISION=Y"]

    name: ${{ matrix.cxx }} and ${{ matrix.cc }} on ${{ matrix.os }} with flag ${{ matrix.cflag }}
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3

    - name: Install Ubuntu dependencies
      if: startsWith(matrix.os, 'ubuntu')
      run: |
        sudo apt-get update
        cat requirements.linux | xargs sudo apt-get install

    - name: Install OSX dependencies
      if: startsWith(matrix.os, 'mac')
      run: |
        brew update
	brew upgrade
        cat requirements.mac | xargs brew install

    - name: CMake Configure
      run: |
        mkdir build
        cd build
        cmake ${{ matrix.cflag }} ..
        make VERBOSE=1

    - name: Test run
      run: |
        cp -R share/run ./run_test
        cd run_test
        ./aether
