# This workflow will install the Aether code and eventually run tests

name: Compilation Test

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        cc: ["gcc"]
        cxx: ["g++"]
        cflag: ["-DUSE_NETCDF=Y", "", "-DUSE_DOUBLE_PRECISION=Y"]

    name: ${{ matrix.cxx }} and ${{ matrix.cc }} on ${{ matrix.os }} with flag ${{ matrix.cflag }}
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        sudo apt install cmake
        sudo apt-get install libnetcdf-dev
        sudo apt install libnetcdf-c++4-dev
        sudo apt-get install -y nlohmann-json-dev
        sudo apt-get install liblapack-dev libblas-dev libboost-dev libarmadillo-dev

    - name: CMake Configure
    - run: |
        mkdir build
        cd build
        cmake ${{ matrix.cflag }} ..
        make -j

    - name: Test run
    - run: |
        cd ..
        cp -R share/run ./run_test
        cd run_test
        ./aether
